name: Send Batch Custom Event to Okay
on:
  workflow_call:
    inputs:
      event:
        description: 'Name of the event'
        required: true
      event_unique_id:
        description: 'The unique id for this event'
        required: true
      user:
        description: 'The github login of the person'
        required: false
      metric1_name:
        description: 'The name of the metric (A)'
        required: false
      metric1_duration_ms:
        description: 'How long something (A) took in milliseconds'
        required: false
      metric2_name:
        description: 'The name of the metric (B)'
        required: false
      metric2_duration_ms:
        description: 'How long something (B) took in milliseconds'
        required: false
      metric3_name:
        description: 'The name of the metric (C)'
        required: false
      metric3_count:
        description: 'Number of times something (C) happened'
        required: false
      metric4_name:
        description: 'The name of the metric (D)'
        required: false
      metric4_count:
        description: 'Number of times something (D) happened'
        required: false
jobs:
  okay-send-custom-event-batch-webhook:
    runs-on: ubuntu-latest
    steps:
    - name: Send Okay Webhook
      env:
        OKAY_API_TOKEN: ${{ secrets.OKAY_API_TOKEN }}
      run: |
        curl -X POST -H "Authorization: Bearer $OKAY_API_TOKEN" -H 'Content-Type: application/json' --data "{\"version\": \"1\", \"type\": \"batch\", \"event\": \"custom\",  \"uniqueKey\": [\"event_unique_id\"], \"customEventName\": \"${{ inputs.event }}\", \"timestamp\": \"$(date +%Y-%m-%dT%H:%M:%S%z)\", \"identity\": {\"user\": \"${{ inputs.user }}\", \"type\": \"sourceControlLogin\"}, \"properties\": {\"event_unique_id\": \"${{ inputs.event_unique_id }}\", \"${{ inputs.metric1_name }}\": \"${{ inputs.metric1_duration_ms }}\", \"${{ inputs.metric2_name }}\": \"${{ inputs.metric2_duration_ms }}\", \"${{ inputs.metric3_name }}\": \"${{ inputs.metric3_count }}\", \"${{ inputs.metric4_name }}\": \"${{ inputs.metric4_count }}\"}}" https://app.okayhq.com/api/events/v1