name: Send Deploy Event to Okay
on:
  workflow_dispatch:
    inputs:
      sha:
        description: 'Deployed Commit SHA'
        required: true
      environment:
        description: 'The target environment of the Deploy'
        required: false
      repo:
        description: 'The source repo deployed'
        required: false
      service:
        description: 'The target service deployed'
        required: false
jobs:
  Okay-Send-Deploy-Webhook:
    runs-on: ubuntu-latest
    steps:
    - name: Send Okay Webhook
      env:
        OKAY_API_TOKEN: ${{ secrets.OKAY_API_TOKEN }}
      run: |
        curl -X POST -H "Authorization: Bearer $OKAY_API_TOKEN" -H 'Content-Type: application/json' --data "{\"event\": \"deploy\", \"timestamp\": \"$(date +%Y-%m-%dT%H:%M:%S%z)\", \"properties\": {\"sha\": \"${{ github.event.inputs.sha }}\", \"environment\": \"${{ github.event.inputs.env }}\", \"repo\": \"${{ github.event.inputs.repo }}\", \"service\": \"${{ github.event.inputs.service }}\"}}" https://app.okayhq.com/api/webhooks/events