name: Run Custom Event Action
on:
  workflow_dispatch:
    inputs:
      event:
        description: 'Name of the event'
        required: true
      event_unique_id:
        description: 'The unique id for this event'
        required: true
      user:
        description: 'The github login of the person'
        required: false
      metric1_duration_ms:
        description: 'How long something took in milliseconds (e.g. lead time)'
        required: false
      metric2_number:
        description: 'The value of a number metric (e.g. percent build failures today)'
        required: false
      metric3_count:
        description: 'Number of times something happened (e.g. number of incidents)'
        required: false
      label:
        description: 'Optional label to add to the event'
        required: false
      url:
        description: 'URL to get more information about the event'
        required: false
jobs:
  okay-custom-event-action:
    uses:  OkayHQ/actions/.github/workflows/custom-event-action.yml@v1
    with:
      event: ${{ inputs.event }}
      event_unique_id: ${{ inputs.event_unique_id }}
      user: ${{ inputs.user }}
      metric1_duration_ms: ${{ inputs.metric1_duration_ms }}
      metric2_number: ${{ inputs.metric2_number }}
      metric3_count: ${{ inputs.metric3_count }}
      label: ${{ inputs.label }}
      url: ${{ inputs.url }}
    secrets:
      OKAY_API_TOKEN: ${{ secrets.OKAY_API_TOKEN }}