name: Run Custom Event Batch Action
on:
  workflow_dispatch:
    inputs:
      event:
        description: 'Name of the event'
        required: true
      event_unique_id:
        description: 'The unique id for this event'
        required: true
      user:
        description: 'The github login of the person'
        required: false
      metric1_name:
        description: 'The name of a latency metric (A) (e.g lead time)'
        required: false
      metric1_duration_ms:
        description: 'How long something (A) took in milliseconds'
        required: false
      metric2_name:
        description: 'The name of a number metric (B) (e.g. percent build failures today)'
        required: false
      metric2_number:
        description: 'The value of B'
        required: false
      metric3_name:
        description: 'The name of a count metric (C) (e.g. number of incidents)'
        required: false
      metric3_count:
        description: 'Number of times something (C) happened'
        required: false
jobs:
  okay-custom-event-action:
    uses:  OkayHQ/actions/.github/workflows/custom-event-action.yml@v1
    with:
      event: ${{ inputs.event }}
      event_unique_id: ${{ inputs.event_unique_id }}
      user: ${{ inputs.user }}
      metric1_name: $${{ inputs.metric1_name }}
      metric1_duration_ms: ${{ inputs.metric1_duration_ms }}
      metric2_name: $${{ inputs.metric2_name }}
      metric2_number: ${{ inputs.metric2_duration_ms }}
      metric3_name: $${{ inputs.metric3_name }}
      metric3_count: ${{ inputs.metric3_count }}
    secrets:
      OKAY_API_TOKEN: ${{ secrets.OKAY_API_TOKEN }}