name: Run Custom Event Count Action
on:
  workflow_dispatch:
    inputs:
      event:
        description: 'Name of the event'
        required: true
      event_unique_id:
        description: 'The unique id for this event'
        required: true
      user:
        description: 'The github login of the person'
        required: false
      metric_name:
        description: 'The name of the count metric'
        required: true
      metric_count:
        description: 'Number of times it happened'
        required: true
jobs:
  okay-custom-event-count-action:
    uses:  OkayHQ/actions/custom-event-count@v1
  with:
    event: ${{ inputs.event }}
    event_unique_id: ${{ inputs.event_unique_id }}
    user: ${{ inputs.user }}
    metric_name: $${{ inputs.metric_name }}
    metric_count: ${{ inputs.metric_count }}
  secrets:
    OKAY_API_TOKEN: ${{ secrets.OKAY_API_TOKEN }}