name: Run Custom Event Batch Action
on:
  workflow_dispatch:
    inputs:
      event:
        description: 'Name of the event'
        required: true
      event_unique_id:
        description: 'The unique id for this event'
        required: true
      user:
        description: 'The github login of the person'
        required: false
      metric1_name:
        description: 'The name of the metric (A)'
        required: false
      metric1_duration_ms:
        description: 'How long something (A) took'
        required: false
      metric2_name:
        description: 'The name of the metric (B)'
        required: false
      metric2_duration_ms:
        description: 'How long something (B) took'
        required: false
      metric3_name:
        description: 'The name of the metric (C)'
        required: false
      metric3_count:
        description: 'Number of times something (C) happened'
        required: false
      metric4_name:
        description: 'The name of the metric (D)'
        required: false
      metric4_count:
        description: 'Number of times something (D) happened'
        required: false
jobs:
  okay-custom-event-batch-action:
    uses:  OkayHQ/actions/custom-event-batch@v1
  with:
    event: ${{ inputs.event }}
    event_unique_id: ${{ inputs.event_unique_id }}
    user: ${{ inputs.user }}
    metric1_name: $${{ inputs.metric1_name }}
    metric1_duration_ms: ${{ inputs.metric1_duration_ms }}
    metric2_name: $${{ inputs.metric2_name }}
    metric2_duration_ms: ${{ inputs.metric2_duration_ms }}
    metric3_name: $${{ inputs.metric3_name }}
    metric3_count: ${{ inputs.metric3_count }}
    metric4_name: $${{ inputs.metric4_name }}
    metric4_count: ${{ inputs.metric4_count }}
  secrets:
    OKAY_API_TOKEN: ${{ secrets.OKAY_API_TOKEN }}