name: Send Deploy Event to Okay
on:
  workflow_call:
    inputs:
      sha:
        description: 'Deployed commit sha'
        required: true
      environment:
        description: 'The target environment of the Deploy (e.g. staging, production)'
        required: true
      repository:
        description: 'The source repository deployed'
        required: true
      organization:
        description: 'The organization the repository belongs to'
        required: true
      service:
        description: 'The target service deployed'
        required: false
      url:
        description: 'Url to get more information on the deployment'
        required: false
    secrets:
      OKAY_API_TOKEN:
        required: true
jobs:
  okay-send-deploy-webhook:
    runs-on: ubuntu-latest
    steps:
    - name: Send Okay Webhook
      env:
        OKAY_API_TOKEN: ${{ secrets.OKAY_API_TOKEN }}
      run: |
        curl -X POST -H "Authorization: Bearer $OKAY_API_TOKEN" -H 'Content-Type: application/json' --data "{\"event\": \"deploy\", \"timestamp\": \"$(date +%Y-%m-%dT%H:%M:%S%z)\", \"properties\": {\"sourceControl\": \"github\", \"sha\": \"${{ inputs.sha }}\", \"environment\": \"${{ inputs.environment }}\", \"repository\": \"$(cut -d'/' -f2 <<<'${{ inputs.repository }}')\", \"service\": \"${{ inputs.service }}\", \"organization\": \"${{ inputs.organization }}\", \"url\": \"${{ inputs.url }}\"}}" https://app.okayhq.com/api/events/v1